### ISSUE TITLE
Converting O to Zero

### ISSUE THREAD

**Issue by callingearth** [365Werk/identitydocuments#15]
Seems like converting the letter 'O' to number zero with $document->parsed->document_number is not enough, it needs to be done as well with $document->parsed->check_document_number.  I had this issue with a document_number that ended with 7910 followed by check_document_number '0' (zero) which was returned as letter 'O' from the google api.

I was able to fix that by adding the following line as line 249 in src/IdentityDocuments.php
$document->parsed->check_document_number = preg_replace($re, $subst, $document->parsed->check_document_number);

I haven't done any exhaustive testing so I don't create a pull request, but this seems to have fixed the problem for me anyway.

**Comment by HergenD** [comment]
Thanks for the issue, I'll look into this

**Comment by HergenD** [comment]
As a slight update, version 2.0 is in the works which will address both this and the other open issue
