### ISSUE TITLE
Laravel 9 support

### ISSUE THREAD

**Issue by danord24** [365Werk/identitydocuments#35]
Hi, found your blog post on reddit /r/laravel really interesting and made for a great read! 

I've ran into a problem when installing your package via composer. I get the following error:

```
Problem 1
    - werk365/identitydocuments[2.0.0-beta, ..., 2.0.4] require illuminate/support ~5|~6|~7|~8 -> found illuminate/support[v5.0.0, ..., 5.8.x-dev, v6.0.0, ..., 6.x-dev, v7.0.0, ..., 7.x-dev, v8.0.0, ..., 8.x-dev] but it conflicts with your root composer.json require (^9.2).
    - Root composer.json requires werk365/identitydocuments ^2.0 -> satisfiable by werk365/identitydocuments[2.0.0-beta, ..., 2.0.4].
```

Which i've narrowed down to the illuminate/support in composer.json 

`"illuminate/support": "~5|~6|~7|~8"`

Would i be right in thinking that adding in `"illuminate/support": "~5|~6|~7|~8|~9"` would solve the issue? I've checked and laravel 9 is using v9.2 for illuminate/support.

I've not got a lot of experience working with open source and PRs. However I'd be happy to create one, but i'm unsure of how to test this with it being a package? Would appreicate any help in getting this fixed, if you have the time.

Thanks.

**Comment by jeffreyvanreenen** [comment]
I get the same error.

**Comment by cemarta7** [comment]
I did a simple pull request and it works fine with Laravel 9.

**Comment by daemonk12** [comment]
I see you have forked and updated the composer.json - are you able to help me install your update via composer require? or if this is not possible, did you just do a git clone in the vendor directory. How did you do the "php artisan vendor:publish" command when you pulled? sorry for the lack of composer knowledge.

**Comment by cemarta7** [comment]
@daemonk12  In composer you do:

`"repositories": [
        {
            "url": "https://github.com/cemarta7/identitydocuments",
            "type": "git"
        }
    ],
"require": {
....
....
"werk365/identitydocuments": "dev-laravel9"
}`

@danord24 You should do this and closed the issue.
